# Site settings
title: My Process
description: >- # this means to ignore newlines until "baseurl:"
  Where I share my learning process. 
baseurl: "/Blog" # the subpath of your site, e.g. /blog
url: "https://whitleynl.github.io" # the base hostname & protocol for your site

# Author settings
author: 
  name: Nathan Whitley
  email: nlwhit81@gmail.com
  
# Build settings
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme 

# Permalinks
permalink: /:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Nathan Whitley

# Social media links
social_links:
  github: https://github.com/Whitleynl
  linkedin: https://www.linkedin.com/in/whitleynl/

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Exclude files or directories from the build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Include additional files or directories in the build
include:
  - _pages

# Configuration for plugins
jekyll_feed:
  path: atom.xml

# Markdown settings
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
